# Generated by Django 4.1.7 on 2023-03-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userKey', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('CreatedAt', models.DateField()),
                ('ModifiedAt', models.DateField()),
            ],
        ),
    ]
